apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: podinfo
  name: podinfo
  namespace: podinfo
spec:
  ports:
  - name: 9898-9898
    port: 9898
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: NodePort
status:
  loadBalancer: {}
